version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-supermock
      - supermock
    networks:
      - supermock-net

  api-supermock:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - test.env
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - supermock-net

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - supermock-net

  api-supemock-migrate:
    image: "migrate/migrate:v4.18.2"
    depends_on:
      - postgres
    env_file:
      - test.env
    networks:
      - supermock-net
    volumes:
      - "./migrations:/migrations"
    command: ["-path", "/migrations/", "-database", "postgresql://postgres_user:postgres_password@postgres:5432/postgres_db?sslmode=disable", "up"]

  supermock:
    build:
      context: ./client2/my-app # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
#    depends_on:
#      - postgres
    networks:
      - supermock-net

networks:
  supermock-net: