version: "3.9"
services:
  go-app:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - test.env
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - supermock

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - supermock

  client-react-app:
    build:
      context: ./client2/my-app # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    depends_on:
#      - postgres
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - supermock

networks:
  supermock: